AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-test

  Sample SAM Template for sam-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.12
    Architectures: [arm64]
    Timeout: 3
    MemorySize: 128

Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/test
      Handler: main.lambda_handler
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:ap-northeast-1:797964065122:test-que

